### ISSUE TITLE
Can't bind to 'canPermit' since it isn't a known property of 'div'.

### ISSUE THREAD

**Issue by constantinosergiou** [grachpower/ngx-role-permissions#3]
Uncaught Error: Template parse errors: Can't bind to 'canPermit' since it isn't a known property of 'div'.

i have installed as per your instructions 
i am use the latest angular version

**Comment by grachpower** [comment]
Hello, @constantinosergiou, i guess your if you should add  `NgxPermissionModule` into `imports: [...]` declaration of your module, where your component in.

If this doesn't help, please try to reproduce the problem https://stackblitz.com/

Thank you!

**Comment by grachpower** [comment]
Cannot represent
